name: publish
on:
  push:
    branches:
      - main
    paths:
      - "packages/*/CHANGELOG.md"
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set_packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_packages
        run: |
          echo "packages=$(
            git diff-tree --no-commit-id --name-only -r \
              --root --diff-filter=AM "$PREVIOUS_GIT_COMMIT" HEAD -- \
              packages/*/CHANGELOG.md \
              | xargs -n1 dirname \
              | xargs -n1 basename \
              | jq --compact-output --raw-input -n '[inputs]'
          )" >> $GITHUB_OUTPUT
        env:
          PREVIOUS_GIT_COMMIT: ${{ github.event.before }}

  publish:
    name: Publish ${{ matrix.package }}
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.matrix.outputs.packages) }}
    defaults:
      run:
        working-directory: ./packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
        working-directory: ./
      - name: Publish
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
